[package]
name = "libjaka-rs"
version = "0.1.2"
edition = "2024"
authors = ["Yixing <yanjizhou312@163.com>"]
readme = "README.md"
repository = "https://github.com/Robot-Exp-Platform/libjaka-rs"
license = "Apache-2.0"
description = "Rust bindings for the Jaka robot"
categories = ["science::robotics"]
keywords = ["jaka", "robot", "libjaka"]

[lib]
name = "libjaka"
crate-type = ["cdylib", "staticlib"]

[dependencies]
pyo3 = { version = "0.24", features = [
    "extension-module",
    "multiple-pymethods",
], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_with = "3.12"
nalgebra = "0.33"
bincode = "1.3"
robot_behavior = "0.3.6"
paste = "1.0"

[features]
default = ["to_py"]
debug = []
ffi = []
to_py = ["pyo3", "ffi", "robot_behavior/to_py"]
